"use strict";
// constants.ts
Object.defineProperty(exports, "__esModule", { value: true });
exports.DIFFICULTY_SHARE_ICONS = exports.TYPE_SHARE_ICONS = exports.TYPE_COLORS = exports.COLORS = exports.TYPE_SUBLABELS = exports.TYPE_LABELS = exports.SPLASH_IMAGE = exports.STORAGE_KEY = void 0;
exports.STORAGE_KEY = "derivative_v4";
exports.SPLASH_IMAGE = "/splash.jpg";
exports.TYPE_LABELS = {
    ROOT: "ROOT",
    SUPPLETIVE: "SUPPLETIVE PAIR",
    GRIMM: "SOUND SHIFT",
    SEMANTIC: "SEMANTIC DRIFT",
    COLLISION: "COLLISION",
    PIE: "DEEP ROOT",
    DECEPTION: "WEIRD DESCENDANT TAGS",
    FALSE_FAMILY: "FALSE FAMILY",
    PHANTOM_ROOT: "INFERRED ROOT",
    IDIOM: "IDIOM SYSTEM",
    BORROWED: "BORROWED LAYER",
    TOPONYM: "PLACE NAMES",
    MATCH: "WORD ↔ GLOSS",
};
exports.TYPE_SUBLABELS = {
    ROOT: "morphological family",
    SUPPLETIVE: "broken paradigm",
    GRIMM: "phonetic machinery",
    SEMANTIC: "meaning drift",
    COLLISION: "language contact",
    PIE: "proto-layer",
    DECEPTION: "french fakeout descendants",
    FALSE_FAMILY: "etymological imposture",
    PHANTOM_ROOT: "reverse inference",
    IDIOM: "fossilized ideology",
    BORROWED: "colonial lexicon",
    TOPONYM: "geographic extraction",
    MATCH: "concept matching",
};
exports.COLORS = {
    bg: "#070605",
    bg2: "#0a0907",
    surface: "#0d0b08",
    surface2: "#141208",
    surface3: "#1a160f",
    gold: "#e8b84b",
    goldDim: "#c8922a",
    goldDark: "#7a5618",
    goldLine: "rgba(232,184,75,0.28)",
    goldGlow: "rgba(232,184,75,0.18)",
    cyan: "#4ecfcf",
    cyanDim: "#2a8f8f",
    cyanGlow: "rgba(78,207,207,0.16)",
    cyanLine: "rgba(78,207,207,0.32)",
    red: "#8b3a3a",
    redGlow: "rgba(139,58,58,0.22)",
    textPrimary: "#e8d8b0",
    textSecondary: "#9a8868",
    textMuted: "#5a4a38",
    textFaint: "#3a2e1c",
    blackLine: "#1e1808",
};
exports.TYPE_COLORS = {
    ROOT: exports.COLORS.goldDim,
    SUPPLETIVE: "#b87820",
    GRIMM: exports.COLORS.cyan,
    SEMANTIC: "#d4732a",
    COLLISION: "#8ab8b8",
    PIE: exports.COLORS.gold,
    DECEPTION: "#d66a37",
    FALSE_FAMILY: "#8f73db",
    PHANTOM_ROOT: "#5bcf94",
    IDIOM: "#c46eb0",
    BORROWED: "#7ab87a",
    TOPONYM: "#4db6ac",
    MATCH: "#63b3ed",
};
exports.TYPE_SHARE_ICONS = {
    ROOT: "Ψ",
    SUPPLETIVE: "≠",
    GRIMM: "∿",
    SEMANTIC: "→",
    COLLISION: "✕",
    PIE: "∴",
    IDIOM: "❝",
    BORROWED: "←",
    TOPONYM: "⊙",
    DECEPTION: "≢",
    FALSE_FAMILY: "≁",
    PHANTOM_ROOT: "∅",
    MATCH: "⇄",
};
exports.DIFFICULTY_SHARE_ICONS = {
    EASY: "○",
    MEDIUM: "◎",
    HARD: "◉",
    VERY_HARD: "●",
};
